[package]
name = "cron-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcron = "1.2.2"
chrono = "0.4.34"
