<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qa.proto

namespace Qa;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 问题实体
 *
 * Generated from protobuf message <code>qa.QuestionEntity</code>
 */
class QuestionEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * 问题id
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * 问题标题
     *
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * 内容，这里只返回部分内容
     *
     * Generated from protobuf field <code>string content = 3;</code>
     */
    protected $content = '';
    /**
     * 创建者
     *
     * Generated from protobuf field <code>string created_by = 4;</code>
     */
    protected $created_by = '';
    /**
     * 问题阅读数
     *
     * Generated from protobuf field <code>uint64 read_count = 5;</code>
     */
    protected $read_count = 0;
    /**
     * 回答数量
     *
     * Generated from protobuf field <code>uint64 reply_count = 6;</code>
     */
    protected $reply_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           问题id
     *     @type string $title
     *           问题标题
     *     @type string $content
     *           内容，这里只返回部分内容
     *     @type string $created_by
     *           创建者
     *     @type int|string $read_count
     *           问题阅读数
     *     @type int|string $reply_count
     *           回答数量
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Qa::initOnce();
        parent::__construct($data);
    }

    /**
     * 问题id
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 问题id
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * 问题标题
     *
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * 问题标题
     *
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * 内容，这里只返回部分内容
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * 内容，这里只返回部分内容
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * 创建者
     *
     * Generated from protobuf field <code>string created_by = 4;</code>
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * 创建者
     *
     * Generated from protobuf field <code>string created_by = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_by = $var;

        return $this;
    }

    /**
     * 问题阅读数
     *
     * Generated from protobuf field <code>uint64 read_count = 5;</code>
     * @return int|string
     */
    public function getReadCount()
    {
        return $this->read_count;
    }

    /**
     * 问题阅读数
     *
     * Generated from protobuf field <code>uint64 read_count = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReadCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->read_count = $var;

        return $this;
    }

    /**
     * 回答数量
     *
     * Generated from protobuf field <code>uint64 reply_count = 6;</code>
     * @return int|string
     */
    public function getReplyCount()
    {
        return $this->reply_count;
    }

    /**
     * 回答数量
     *
     * Generated from protobuf field <code>uint64 reply_count = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReplyCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->reply_count = $var;

        return $this;
    }

}

