[package]
name = "rs-python-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# pyo3包需要开启auto-initialize feature
pyo3 = { version = "0.21.1", features = ["auto-initialize"] }
