app_debug: true # 是否开启调试模式
app_port: 3000 # http service运行端口
graceful_wait_time: 3 # http service平滑退出等待时间
mysql_conf:
  dsn: "mysql://root:root123456@localhost/points_sys" # dsn连接句柄信息
  max_connections: 100 # 最大连接数，默认为500
  min_connections: 10  # 最小连接数，默认为10
  max_lifetime: 1800  # 连接池默认生命周期，默认为1800s
  idle_timeout: 300   # 空闲连接生命周期超时，默认为300s
  connect_timeout: 10 # 连接超时时间，默认为10s

pulsar_conf:
  addr: pulsar://127.0.0.1:6650
  token: "" # pulsar auth token
