[package]
name = "murmurhash3-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
murmurhash32 = "0.3.0"
base62 = "2.0.2"
murmurhash3 = "0.0.5"

