[package]
name = "murmurhash3-demo"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
murmurhash32 = "0.3.1"
base62 = "2.2.1"
murmurhash3 = "0.0.5"

