<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qa.proto

namespace GPBMetadata;

class Qa
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Á
qa.protoqa"6
UserLoginRequest
username (	
password (	"
UserLoginReply
token (	"%
UserLogoutRequest
username (	" 
UserLogoutReply
state ("9
UserRegisterRequest
username (	
password (	""
UserRegisterReply
state ("H
AddQuestionRequest
title (	
content (	

created_by (	"
AddQuestionReply

id ("5
DeleteQuestionRequest

id (
username (	"$
DeleteQuestionReply
state ("W
UpdateQuestionRequest

id (
title (	
content (	

updated_by (	"$
UpdateQuestionReply
state ("}
AnswerEntity

id (
question_id (
content (	

created_by (	
agree_count (

has_agreed ("4
AddAnswerRequest 
answer (2.qa.AnswerEntity"
AddAnswerReply

id ("3
DeleteAnswerRequest

id (
username (	""
DeleteAnswerReply
state ("D
UpdateAnswerRequest

id (
content (	
username (	""
UpdateAnswerReply
state ("4
AnswerAgreeRequest

id (

created_by (	"3
AnswerAgreeReply

id (
agree_count ("8
QuestionReadCountRequest

id (
username (	"8
QuestionReadCountReply

id (

read_count ("5
QuestionDetailRequest

id (
username (	";
QuestionDetailReply$
question (2.qa.QuestionEntity"w
QuestionEntity

id (
title (	
content (	
username (	

read_count (
reply_count (";
LatestQuestionsRequest
username (	
last_id ("h
LatestQuestionsReply 
list (2.qa.QuestionEntity
last_id (
limit (
is_end ("W
AnswerListRequest
question_id (
page (
limit (
username (	"d
AnswerListReply
list (2.qa.AnswerEntity
total (

total_page (
is_end (2‘
	QAService5
	UserLogin.qa.UserLoginRequest.qa.UserLoginReply8

UserLogout.qa.UserLogoutRequest.qa.UserLogoutReply>
UserRegister.qa.UserRegisterRequest.qa.UserRegisterReply;
AddQuestion.qa.AddQuestionRequest.qa.AddQuestionReplyD
DeleteQuestion.qa.DeleteQuestionRequest.qa.DeleteQuestionReplyD
UpdateQuestion.qa.UpdateQuestionRequest.qa.UpdateQuestionReplyD
QuestionDetail.qa.QuestionDetailRequest.qa.QuestionDetailReplyG
LatestQuestions.qa.LatestQuestionsRequest.qa.LatestQuestionsReply8

AnswerList.qa.AnswerListRequest.qa.AnswerListReply5
	AddAnswer.qa.AddAnswerRequest.qa.AddAnswerReply>
DeleteAnswer.qa.DeleteAnswerRequest.qa.DeleteAnswerReply>
UpdateAnswer.qa.UpdateAnswerRequest.qa.UpdateAnswerReply;
AnswerAgree.qa.AnswerAgreeRequest.qa.AnswerAgreeReplyM
QuestionReadCount.qa.QuestionReadCountRequest.qa.QuestionReadCountReplyBZ.;pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

