<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qa.proto

namespace App\Grpc\Qa;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 验证token返回结果
 *
 * Generated from protobuf message <code>qa.VerifyTokenReply</code>
 */
class VerifyTokenReply extends \Google\Protobuf\Internal\Message
{
    /**
     * 1表示验证成功，0验证失败
     *
     * Generated from protobuf field <code>int64 state = 1;</code>
     */
    protected $state = 0;
    /**
     * 验证失败返回具体的提示信息
     *
     * Generated from protobuf field <code>string reason = 2;</code>
     */
    protected $reason = '';
    /**
     * 当前用户username
     *
     * Generated from protobuf field <code>string username = 3;</code>
     */
    protected $username = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $state
     *           1表示验证成功，0验证失败
     *     @type string $reason
     *           验证失败返回具体的提示信息
     *     @type string $username
     *           当前用户username
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Qa::initOnce();
        parent::__construct($data);
    }

    /**
     * 1表示验证成功，0验证失败
     *
     * Generated from protobuf field <code>int64 state = 1;</code>
     * @return int|string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * 1表示验证成功，0验证失败
     *
     * Generated from protobuf field <code>int64 state = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkInt64($var);
        $this->state = $var;

        return $this;
    }

    /**
     * 验证失败返回具体的提示信息
     *
     * Generated from protobuf field <code>string reason = 2;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * 验证失败返回具体的提示信息
     *
     * Generated from protobuf field <code>string reason = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * 当前用户username
     *
     * Generated from protobuf field <code>string username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * 当前用户username
     *
     * Generated from protobuf field <code>string username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

}

