// qml/main.qml 文件定义

// 引入qt基本组件
import QtQuick 2.12;
import QtQuick.Controls 2.12;
import QtQuick.Window 2.12;
import QtQuick.Controls.Basic 2.12;

// 这里导入的包名必须要 build.rs文件中的uri:"cxx_qt.myapp"一致
import cxx_qt.myapp 1.0;

// 定义窗口应用程序
Window {
    title: qsTr("cxx-qt-app")
    visible: true
    height: 480
    width: 640
    color: "#ffffff"

    Hello {
        // id表示每个对象元素的唯一标识
        id: hello
        plain: "" // plain是一个QString字符串类型
    }

    RandObj {
        id: rand_obj
        number: 0 // number是一个i32数字类型,对应rust的i32数字类型
        number2: 0 // number2是一个i32数字类型，对应js的number数字类型
    }

    Column {
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.verticalCenter: parent.verticalCenter
        /* space between widget */
        spacing: 10

        // 点击Say Hello按钮下方显示 hello,world
        Button {
            text: "Say Hello"
            onClicked: {
                // 支持js es5/es6语法
                console.log("call say_hello from rust cxx-qt-app");
                // 调用Hello上面的say_hello方法，这里的say_hello需要采用驼峰格式
                let s = hello.sayHello();
                // 将结果赋值给hello.plain字段
                hello.plain = s;
            }
        }

        Label {
            text: hello.plain
            font.bold: true
        }

        // 通过rust生成一个随机数
        Button {
            text: "gen a rand number by rust"
            onClicked: {
                // qt qml文件支持js语法，也就是说支持js es5/es6语法
                let rnd = rand_obj.genNumber(1, 101);
                console.log("gen random number: ", rnd);
                rand_obj.number = rnd;
            }
        }

        Label {
            text: "the random number generated by rust is: " + rand_obj.number
        }

        // 通过js提供的Math.random函数生成一个随机数
        Button {
            text: "gen a rand number by js"
            onClicked: {
                // 生成1-100的随机数字
                let m = 1;
                let n = 100;
                let rnd = Math.floor(Math.random() * (n - m)) + m;
                console.log("gen js random number: ", rnd);
                rand_obj.number2 = rnd
            }
        }

        Label {
            text: "the random number generated by js is: " + rand_obj.number2
        }
    }
}
