<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qa.proto

namespace Qa;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 问题详情，返回结果
 *
 * Generated from protobuf message <code>qa.QuestionDetailReply</code>
 */
class QuestionDetailReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.qa.QuestionEntity question = 1;</code>
     */
    protected $question = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Qa\QuestionEntity $question
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Qa::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.qa.QuestionEntity question = 1;</code>
     * @return \Qa\QuestionEntity|null
     */
    public function getQuestion()
    {
        return $this->question;
    }

    public function hasQuestion()
    {
        return isset($this->question);
    }

    public function clearQuestion()
    {
        unset($this->question);
    }

    /**
     * Generated from protobuf field <code>.qa.QuestionEntity question = 1;</code>
     * @param \Qa\QuestionEntity $var
     * @return $this
     */
    public function setQuestion($var)
    {
        GPBUtil::checkMessage($var, \Qa\QuestionEntity::class);
        $this->question = $var;

        return $this;
    }

}

